version: '3'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: dev
    # image: strapi/strapi
    environment:
      DATABASE_CLIENT: mongo
      DATABASE_NAME: strapi
      DATABASE_HOST: db
      DATABASE_PORT: 27017
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi
    volumes:
      - ./backend:/srv/app
      - /srv/app/node_modules
    ports:
      - '1337:1337'
    depends_on:
      - db
    command: npm run develop
    networks:
      - app-network
  db:
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: strapi
      MONGO_INITDB_ROOT_USERNAME: strapi
      MONGO_INITDB_ROOT_PASSWORD: strapi
    volumes:
      - strapidata-mongo:/data/db
    networks:
      - app-network
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: dev
    volumes:
      - ./frontend/:/code
      - /code/node_modules
    ports:
      - "3000:3000"
      - "8080:8080"
    depends_on:
      - backend
    command: npm run develop
    # command: npx http-server -p 8080 ./out
    networks:
      - app-network
  reverse_proxy:
    image: nginx
    volumes:
      - ./reverse-proxy/:/etc/nginx/
    ports:
      - 80:80
    networks:
      - app-network
    depends_on:
      - backend
      - frontend

networks:
  app-network:
    driver: bridge

volumes:
  strapidata-mongo:
